export const menuTree = [
  {
    id: 1,
    name: 'Dashboard',
    status: 1,
    type: 'menu',
    icon: 'mdi:dashboard',
    path: '/analytics',
    component: '/dashboard/analytics/index',
    meta: {
      icon: 'lucide:layout-dashboard',
      title: 'page.dashboard.title',
      affixTab: true,
      order: 0,
    },
  },
  {
    id: 2,
    meta: {
      icon: 'ion:settings-outline',
      order: 100,
      title: 'system.title',
      badge: 'new',
      badgeType: 'normal',
      badgeVariants: 'primary',
    },
    status: 1,
    type: 'menu',
    name: 'System',
    path: '/system',
    children: [
      {
        id: 201,
        pid: 2,
        path: '/system/role',
        name: 'SystemRole',
        authCode: 'System:Role:List',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'mdi:account-group',
          title: 'system.role.title',
        },
        component: '/system/role/list',
        children: [
          {
            id: 20101,
            pid: 201,
            name: 'SystemRoleCreate',
            status: 1,
            type: 'button',
            authCode: 'System:Role:Create',
            meta: {
              title: 'common.create',
            },
          },
          {
            id: 20102,
            pid: 201,
            name: 'SystemRoleEdit',
            status: 1,
            type: 'button',
            authCode: 'System:Role:Edit',
            meta: {
              title: 'common.edit',
            },
          },
          {
            id: 20103,
            pid: 201,
            name: 'SystemRoleDelete',
            status: 1,
            type: 'button',
            authCode: 'System:Role:Delete',
            meta: {
              title: 'common.delete',
            },
          },
          {
            id: 20104,
            pid: 201,
            name: 'SystemRolePermission',
            status: 1,
            type: 'button',
            authCode: 'System:Role:Permission',
            meta: {
              title: 'common.setPermissions',
            },
          },
        ],
      },
      {
        id: 202,
        pid: 2,
        path: '/system/user',
        name: 'SystemUser',
        status: 1,
        type: 'menu',
        authCode: 'System:User:List',
        meta: {
          icon: 'solar:users-group-rounded-broken',
          title: 'system.user.title',
        },
        component: '/system/user/list',
        children: [
          {
            id: 20201,
            pid: 202,
            name: 'SystemUserCreate',
            status: 1,
            type: 'button',
            authCode: 'System:User:Create',
            meta: {
              title: 'common.create',
            },
          },
          {
            id: 20202,
            pid: 202,
            name: 'SystemUserEdit',
            status: 1,
            type: 'button',
            authCode: 'System:User:Edit',
            meta: {
              title: 'common.edit',
            },
          },
          {
            id: 20203,
            pid: 202,
            name: 'SystemUserDelete',
            status: 1,
            type: 'button',
            authCode: 'System:User:Delete',
            meta: {
              title: 'common.delete',
            },
          },
          {
            id: 20204,
            pid: 202,
            name: 'SystemUserReset',
            status: 1,
            type: 'button',
            authCode: 'System:User:Reset',
            meta: {
              title: 'common.reset',
            },
          },
        ],
      },
      {
        id: 203,
        pid: 2,
        path: '/system/log',
        name: 'SystemLog',
        status: 1,
        type: 'menu',
        authCode: 'System:Log:List',
        meta: {
          icon: 'iconoir:journal',
          title: 'system.log.title',
        },
        component: '/system/log/list',
      },
    ],
  },
  {
    id: 3,
    meta: {
      icon: 'material-symbols:monitor-heart-outline',
      order: 10,
      title: 'monitor.title',
    },
    status: 1,
    type: 'menu',
    name: 'Monitor',
    path: '/monitor',
    children: [
      {
        id: 301,
        pid: 3,
        path: '/monitor/device',
        name: 'MonitorDevice',
        authCode: 'Monitor:Device:List',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'ic:baseline-device-hub',
          title: 'monitor.device.title',
        },
        component: '/monitor/device/index',
        children: [
          {
            id: 30101,
            pid: 301,
            name: 'MonitorDeviceDetail',
            status: 1,
            type: 'button',
            authCode: 'Monitor:Device:Detail',
            meta: {
              title: 'common.detail',
            },
          },
        ],
      },
    ],
  },
  {
    id: 4,
    meta: {
      icon: 'streamline:interface-edit-clip-binder-clip-clipper-company-office-supplies-work',
      order: 20,
      title: 'loan.company.title',
    },
    status: 1,
    type: 'menu',
    name: 'Company',
    path: '/company',
    component: '/loan/company/list',
    children: [
      {
        id: 40101,
        pid: 4,
        name: 'CompanyCreate',
        status: 1,
        type: 'button',
        authCode: 'Company:Create',
        meta: {
          title: 'common.create',
        },
      },
      {
        id: 40102,
        pid: 4,
        name: 'CompanyEdit',
        status: 1,
        type: 'button',
        authCode: 'Company:Edit',
        meta: {
          title: 'common.edit',
        },
      },
      {
        id: 40103,
        pid: 4,
        name: 'CompanyDelete',
        status: 1,
        type: 'button',
        authCode: 'Company:Delete',
        meta: {
          title: 'common.delete',
        },
      },
      {
        id: 40104,
        pid: 4,
        name: 'CompanyDetail',
        status: 1,
        type: 'button',
        authCode: 'Company:Detail',
        meta: {
          title: 'common.detail',
        },
      },
    ],
  },
  {
    id: 5,
    meta: {
      icon: 'flowbite:users-group-solid',
      order: 30,
      title: 'loan.user.title',
    },
    status: 1,
    type: 'menu',
    name: 'User',
    path: '/user',
    component: '/loan/user/list',
    children: [
      {
        id: 50101,
        pid: 5,
        name: 'UserCreate',
        status: 1,
        type: 'button',
        authCode: 'User:Create',
        meta: {
          title: 'common.create',
        },
      },
      {
        id: 50102,
        pid: 5,
        name: 'UserEdit',
        status: 1,
        type: 'button',
        authCode: 'User:Edit',
        meta: {
          title: 'common.edit',
        },
      },
      {
        id: 50103,
        pid: 5,
        name: 'UserDelete',
        status: 1,
        type: 'button',
        authCode: 'User:Delete',
        meta: {
          title: 'common.delete',
        },
      },
      {
        id: 50104,
        pid: 5,
        name: 'UserDetail',
        status: 1,
        type: 'button',
        authCode: 'User:Detail',
        meta: {
          title: 'common.detail',
        },
      },
    ],
  },
  {
    id: 6,
    meta: {
      icon: 'material-symbols:perm-data-setting-rounded',
      order: 40,
      title: 'data.title',
    },
    status: 1,
    type: 'menu',
    name: 'Data',
    path: '/data',
    children: [
      {
        id: 601,
        pid: 6,
        path: '/data/import',
        name: 'DataImport',
        authCode: 'Data:Import',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'solar:import-bold',
          title: 'data.import.title',
        },
        component: '/data/import',
        children: [
          {
            id: 60101,
            pid: 601,
            name: 'DataImportDownload',
            status: 1,
            type: 'button',
            authCode: 'Data:Import:Download',
            meta: {
              title: 'data.import.download',
            },
          },
          {
            id: 60102,
            pid: 601,
            name: 'DataImportUpload',
            status: 1,
            type: 'button',
            authCode: 'Data:Import:Upload',
            meta: {
              title: 'data.import.upload',
            },
          },
          {
            id: 60103,
            pid: 601,
            name: 'DataImportSubmit',
            status: 1,
            type: 'button',
            authCode: 'Data:Import:Submit',
            meta: {
              title: 'data.import.submit',
            },
          },
        ],
      },
      {
        id: 602,
        pid: 6,
        path: '/data/record',
        name: 'DataRecord',
        authCode: 'Data:Record:List',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'material-symbols:event-list',
          title: 'data.record.title',
        },
        component: '/data/list',
        children: [
          {
            id: 60201,
            pid: 602,
            name: 'DataRecordDownload',
            status: 1,
            type: 'button',
            authCode: 'Data:Record:Download',
            meta: {
              title: 'data.record.download',
            },
          },
          {
            id: 60202,
            pid: 602,
            name: 'DataRecordDelete',
            status: 1,
            type: 'button',
            authCode: 'Data:Record:Delete',
            meta: {
              title: 'common.delete',
            },
          },
        ],
      },
    ],
  },
  {
    id: 7,
    meta: {
      icon: 'mingcute:user-info-line',
      order: 50,
      title: 'info.title',
    },
    status: 1,
    type: 'menu',
    name: 'Info',
    path: '/info',
    children: [
      {
        id: 701,
        pid: 7,
        path: '/info/agreement',
        name: 'InfoAgreement',
        authCode: 'Info:Agreement',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'hugeicons:agreement-02',
          title: 'info.agreement.title',
        },
        component: '/info/agreement/list',
        children: [
          {
            id: 70101,
            pid: 701,
            name: 'InfoAgreementCreate',
            status: 1,
            type: 'button',
            authCode: 'Info:Agreement:Create',
            meta: {
              title: 'common.create',
            },
          },
          {
            id: 70102,
            pid: 701,
            name: 'InfoAgreementEdit',
            status: 1,
            type: 'button',
            authCode: 'Info:Agreement:Edit',
            meta: {
              title: 'common.edit',
            },
          },
          {
            id: 70103,
            pid: 701,
            name: 'InfoAgreementDelete',
            status: 1,
            type: 'button',
            authCode: 'Info:Agreement:Delete',
            meta: {
              title: 'common.delete',
            },
          },
          {
            id: 70104,
            pid: 701,
            name: 'InfoAgreementDetail',
            status: 1,
            type: 'button',
            authCode: 'Info:Agreement:Detail',
            meta: {
              title: 'common.detail',
            },
          },
          {
            id: 70105,
            pid: 701,
            name: 'InfoAgreementRepayment',
            status: 1,
            type: 'button',
            authCode: 'Info:Agreement:Repayment',
            meta: {
              title: 'info.agreement.repayment',
            },
          },
        ],
      },
      {
        id: 702,
        pid: 7,
        path: '/info/repayment',
        name: 'InfoRepayment',
        authCode: 'Info:Repayment',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'ic:outline-import-contacts',
          title: 'info.repayment.title',
        },
        component: '/info/repayment/list',
        children: [
          {
            id: 70201,
            pid: 702,
            name: 'InfoRepaymentDetail',
            status: 1,
            type: 'button',
            authCode: 'Info:Repayment:Detail',
            meta: {
              title: 'common.detail',
            },
          },
          {
            id: 70202,
            pid: 702,
            name: 'InfoRepaymentRepayment',
            status: 1,
            type: 'button',
            authCode: 'Info:Repayment:Repayment',
            meta: {
              title: 'info.agreement.repayment',
            },
          },
        ],
      },
    ],
  },
  {
    id: 8,
    meta: {
      icon: 'material-symbols:assistant-device-outline',
      order: 60,
      title: 'car.device.title',
    },
    status: 1,
    type: 'menu',
    name: 'Device',
    path: '/device',
    component: '/device/list',
    children: [
      {
        id: 80101,
        pid: 801,
        name: 'DeviceCreate',
        status: 1,
        type: 'button',
        authCode: 'Device:Create',
        meta: {
          title: 'common.create',
        },
      },
      {
        id: 80102,
        pid: 801,
        name: 'DeviceEdit',
        status: 1,
        type: 'button',
        authCode: 'Device:Edit',
        meta: {
          title: 'common.edit',
        },
      },
      {
        id: 80103,
        pid: 801,
        name: 'DeviceDelete',
        status: 1,
        type: 'button',
        authCode: 'Device:Delete',
        meta: {
          title: 'common.delete',
        },
      },
      {
        id: 80104,
        pid: 801,
        name: 'DeviceDetail',
        status: 1,
        type: 'button',
        authCode: 'Device:Detail',
        meta: {
          title: 'common.detail',
        },
      },
      {
        id: 80105,
        pid: 801,
        name: 'DeviceOn',
        status: 1,
        type: 'button',
        authCode: 'Device:On',
        meta: {
          title: 'car.device.operate.on',
        },
      },
      {
        id: 80106,
        pid: 801,
        name: 'DeviceOff',
        status: 1,
        type: 'button',
        authCode: 'Device:Off',
        meta: {
          title: 'car.device.operate.off',
        },
      },
    ],
  },
  {
    id: 9,
    meta: {
      icon: 'material-symbols:emoji-transportation-sharp',
      order: 70,
      title: 'car.title',
    },
    status: 1,
    type: 'menu',
    name: 'Car',
    path: '/car',
    children: [
      {
        id: 901,
        pid: 9,
        name: 'CarBrand',
        path: '/car/brand',
        authCode: 'Car:Brand:List',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'ic:outline-branding-watermark',
          title: 'car.brand.title',
        },
        component: '/car/brand/list',
        children: [
          {
            id: 90101,
            pid: 901,
            name: 'CarBrandCreate',
            status: 1,
            type: 'button',
            authCode: 'Car:Brand:Create',
            meta: {
              title: 'common.create',
            },
          },
          {
            id: 90102,
            pid: 901,
            name: 'CarBrandEdit',
            status: 1,
            type: 'button',
            authCode: 'Car:Brand:Edit',
            meta: {
              title: 'common.edit',
            },
          },
          {
            id: 90103,
            pid: 901,
            name: 'CarBrandDelete',
            status: 1,
            type: 'button',
            authCode: 'Car:Brand:Delete',
            meta: {
              title: 'common.delete',
            },
          },
          {
            id: 90104,
            pid: 901,
            name: 'CarBrandDetail',
            status: 1,
            type: 'button',
            authCode: 'Car:Brand:Detail',
            meta: {
              title: 'common.detail',
            },
          },
        ],
      },
      {
        id: 902,
        pid: 9,
        name: 'CarVehicle',
        path: '/car/vehicle',
        authCode: 'Car:Vehicle:List',
        status: 1,
        type: 'menu',
        meta: {
          icon: 'material-symbols:car-gear-outline-rounded',
          title: 'car.vehicle.title',
        },
        component: '/car/vehicle/list',
        children: [
          {
            id: 90201,
            pid: 902,
            name: 'CarVehicleCreate',
            status: 1,
            type: 'button',
            authCode: 'Car:Vehicle:Create',
            meta: {
              title: 'common.create',
            },
          },
          {
            id: 90202,
            pid: 902,
            name: 'CarVehicleEdit',
            status: 1,
            type: 'button',
            authCode: 'Car:Vehicle:Edit',
            meta: {
              title: 'common.edit',
            },
          },
          {
            id: 90203,
            pid: 902,
            name: 'CarVehicleDelete',
            status: 1,
            type: 'button',
            authCode: 'Car:Vehicle:Delete',
            meta: {
              title: 'common.delete',
            },
          },
          {
            id: 90204,
            pid: 902,
            name: 'CarVehicleDetail',
            status: 1,
            type: 'button',
            authCode: 'Car:Vehicle:Detail',
            meta: {
              title: 'common.detail',
            },
          },
        ],
      },
    ],
  },
  {
    id: 10,
    meta: {
      icon: 'material-symbols:policy',
      order: 80,
      title: 'policy.title',
    },
    status: 1,
    type: 'menu',
    name: 'Policy',
    path: '/policy',
    component: '/policy/list',
    children: [
      {
        id: 100101,
        pid: 1001,
        name: 'PolicyCreate',
        status: 1,
        type: 'button',
        authCode: 'Policy:Create',
        meta: {
          title: 'common.create',
        },
      },
      {
        id: 100102,
        pid: 1001,
        name: 'PolicyEdit',
        status: 1,
        type: 'button',
        authCode: 'Policy:Edit',
        meta: {
          title: 'common.edit',
        },
      },
      {
        id: 100103,
        pid: 1001,
        name: 'PolicyDelete',
        status: 1,
        type: 'button',
        authCode: 'Policy:Delete',
        meta: {
          title: 'common.delete',
        },
      },
      {
        id: 100104,
        pid: 1001,
        name: 'PolicyDetail',
        status: 1,
        type: 'button',
        authCode: 'Policy:Detail',
        meta: {
          title: 'common.detail',
        },
      },
      {
        id: 100105,
        pid: 1001,
        name: 'DeviceStatus',
        status: 1,
        type: 'button',
        authCode: 'Device:Status',
        meta: {
          title: 'common.status',
        },
      },
    ],
  },
];
